### ISSUE TITLE
[Solved] Error in installation

### ISSUE THREAD

**Issue by neoyukito** [magicbookproject/magicbook#15]
### I have this error in a clean installation.
----
Steps

➜  MINIZINC cd magicbook 
➜  magicbook ls
➜  magicbook npm install magicbook -g
/usr/local/bin/magicbook -> /usr/local/lib/node_modules/magicbook/src/index.js

> fsevents@1.1.2 install /usr/local/lib/node_modules/magicbook/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/magicbook/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> node-sass@3.13.1 install /usr/local/lib/node_modules/magicbook/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-51_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /usr/local/lib/node_modules/magicbook/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Caching binary to /Users/Salazar/.npm/node-sass/3.13.1/darwin-x64-51_binding.node

> prince@1.4.2 install /usr/local/lib/node_modules/magicbook/node_modules/prince
> node ./prince-npm.js install

++ checking for globally installed PrinceXML
++ downloading PrinceXML distribution
-- download: http://www.princexml.com/download/prince-11.3-macosx.tar.gz
-- download: [########################################] 100% (ETA: 0.0s)
-- download: 7031296 bytes received.
++ locally unpacking PrinceXML distribution
**# ERROR: failed to extract: TypeError: tar.Extract is not a function**

> node-sass@3.13.1 postinstall /usr/local/lib/node_modules/magicbook/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/lib/node_modules/magicbook/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine
/usr/local/lib
└─┬ magicbook@0.1.12 
  ├── async@1.5.2 
  ├─┬ cheerio@0.20.0 

...
...
➜  magicbook magicbook new minizinc-es
Created folder: minizinc-es
➜  magicbook cd minizinc-es 
➜  minizinc-es magicbook build
Config file detected: magicbook.json
/usr/local/lib/node_modules/magicbook/node_modules/prince/prince-api.js:242
            throw new Error("Prince#" + method + ": cannot resolve binary \"" +
            ^

Error: Prince#execute: cannot resolve binary "prince" to a filesystem path
    at Prince._execute (/usr/local/lib/node_modules/magicbook/node_modules/prince/prince-api.js:242:19)
    at Prince.execute (/usr/local/lib/node_modules/magicbook/node_modules/prince/prince-api.js:298:17)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/magicbook/src/plugins/pdf.js:51:10)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:188:7)
    at finishMaybe (/usr/local/lib/node_modules/magicbook/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at afterWrite (/usr/local/lib/node_modules/magicbook/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:470:3)
    at onwrite (/usr/local/lib/node_modules/magicbook/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:461:7)
    at WritableState.onwrite (/usr/local/lib/node_modules/magicbook/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/usr/local/lib/node_modules/magicbook/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:3)

**Comment by h0d** [comment]
This seems to be caused because of a bug in the `prince` module.

Here's a workaround:
`cd /usr/local/lib/node_modules/magicbook/node_modules/prince`
`sed -i '' 's/Extract/extract/g' prince-npm.js`
`sed -i '' 's/prince\/lib/lib/g' prince-api.js`
`node ./prince-npm.js install`

Otherwise, install `prince` with Homebrew:
`brew cask install prince`

Once you have done either of the above, you can `magicbook build`.

**Comment by neoyukito** [comment]
It's work now.
thanks :)
